FROM node:18
WORKDIR /usr/src/app

COPY auth-service/package*.json ./

# Instalar dependencias y reconstruir bcrypt para Linux
RUN npm install --legacy-peer-deps && npm rebuild bcrypt --build-from-source

COPY auth-service/ .
EXPOSE 8080
CMD ["node", "index.js"]

