services:
  auth-service:
    build:
      context: ../ 
      dockerfile: infrastructure/Dockerfile.auth-service 
    ports:
      - "8080:8080"
    container_name: auth-service
    environment:
      - NODE_ENV=production
    volumes:
      - ../auth-service:/usr/src/app

