# Docker Compose file
version: '3.8'

services:
  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: auth-service
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      KEY_VAULT_NAME: ${KEY_VAULT_NAME}
    volumes:
      - ../auth-service:/usr/src/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  default:
    driver: bridge

