version: '3.8'
services:
  auth-service:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile.auth-service
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

