# Dockerfile para auth-service
FROM node:18

# Establecer el directorio de trabajo
WORKDIR /usr/src/app

# Copiar archivos de configuración
COPY auth-service/package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el código fuente
COPY auth-service/ .

# Exponer el puerto
EXPOSE 8080

# Comando para iniciar el servidor
CMD ["npm", "start"]

