name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Step 3: Install dependencies with specific handling for bcrypt
    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps
        npm rebuild bcrypt --build-from-source

    # Step 4: Run lint to ensure code style
    - name: Run lint
      run: npm run lint

    # Step 5: Run tests to verify functionality
    - name: Run tests
      run: npm test

    # Step 6: Build Docker image
    - name: Build Docker image
      run: docker-compose -f infrastructure/docker-compose.yml build --no-cache

    # Step 7: Run Docker container and check health
    - name: Run Docker container and check health
      run: |
        docker-compose -f infrastructure/docker-compose.yml up -d
        sleep 10
        curl http://localhost:8080/health

    # Step 8: Stop Docker containers
    - name: Stop containers
      run: docker-compose -f infrastructure/docker-compose.yml down

