name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps
          npm install bcrypt --build-from-source

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: |
          docker-compose -f infrastructure/docker-compose.yml build --no-cache

      - name: Run Docker container and check health
        run: |
          docker-compose -f infrastructure/docker-compose.yml up -d
          sleep 10
          curl http://localhost:8080/health

